version: '3'
services:
  server:
    build: ./
    ports:
     - "8080:8080"
    depends_on:
      - "pg_container"
    environment:
      - IN_CONTAINER=true
  pg_container:
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: socket
      POSTGRES_PASSWORD: socketpass